name: Release Bot

on:
  release:
    types:
      - published

jobs:
  build-ea:
    if: "github.event.release.prerelease"
    runs-on: ubuntu-latest
    environment: 'ea'
    steps:

      - name: Hello
        run: |
          echo "EA_SECRET: ${{ secrets.EA_SECRET }}"
          echo "PROD_SECRET: ${{ secrets.PROD_SECRET }}"

  build-prod:
    if: "!github.event.release.prerelease"
    runs-on: ubuntu-latest
    environment: 'prod'
    steps:

      - name: Hello
        run: |
          echo "EA_SECRET: ${{ secrets.EA_SECRET }}"
          echo "PROD_SECRET: ${{ secrets.PROD_SECRET }}"
